[package]
name = "testcontainers_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
testcontainers = "0.14.0"
postgres = "0.19.3"
refinery = { version = "0.8.4", features = ["postgres"] }
