[package]
name = "testcontainers_test"
version = "0.1.0"
edition = "2021"

[lib]
path = "./src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "testcontainers_test"

[dependencies]
actix-web = "4.1.0"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
deadpool-sqlite = "0.3.1"
refinery = { version = "0.8.4", features = ["rusqlite"] }
serde = { version = "1.0.137", features = ["derive"] }
snafu = "0.7.1"

[dev-dependencies]
reqwest = { version = "0.11.11", features = ["json"] }
