[package]
name = "testcontainers_test"
version = "0.1.0"
edition = "2021"

[lib]
path = "./src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "testcontainers_test"

[dependencies]
tokio-postgres = "0.7.6"
actix-web = "4.1.0"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
deadpool-postgres = "0.10.2"
refinery = { version = "0.8.4", features = ["postgres"] }
serde = { version = "1.0.137", features = ["derive"] }

[dev-dependencies]
testcontainers = "0.14.0"
reqwest = { version = "0.11.11", features = ["json"] }
